export const emoji=[
    {"emoji": "😂", "name": "face with tears of joy", "shortname": ":joy:", "unicode": "1f602", "html": "&#128514;", "category": "Smileys & Emotion (face-smiling)", "order": "3"},
    {"emoji": "🙊", "name": "speak-no-evil monkey", "shortname": ":speak_no_evil:", "unicode": "1f64a", "html": "&#128586;", "category": "Smileys & Emotion (monkey-face)", "order": "98"},
    {"emoji": "😍", "name": "smiling face with heart-eyes", "shortname": ":heart_eyes:", "unicode": "1f60d", "html": "&#128525;", "category": "Smileys & Emotion (face-affection)", "order": "13"},
    {"emoji": "😭", "name": "loudly crying face", "shortname": ":sob:", "unicode": "1f62d", "html": "&#128557;", "category": "Smileys & Emotion (face-concerned)", "order": "55"},
    {"emoji": "😊", "name": "smiling face with smiling eyes", "shortname": ":blush:", "unicode": "1f60a", "html": "&#128522;", "category": "Smileys & Emotion (face-smiling)", "order": "10"},
    {"emoji": "😒", "name": "unamused face", "shortname": ":unamused:", "unicode": "1f612", "html": "&#128530;", "category": "Smileys & Emotion (face-neutral-skeptical)", "order": "41"},
    {"emoji": "😩", "name": "weary face", "shortname": ":weary:", "unicode": "1f629", "html": "&#128553;", "category": "Smileys & Emotion (face-concerned)", "order": "59"},
    {"emoji": "👌", "name": "OK hand", "shortname": ":ok_hand:", "unicode": "1f44c", "html": "&#128076;", "category": "People & Body (hand-fingers-partial)", "order": "1170"},
    {"emoji": "😔", "name": "pensive face", "shortname": ":pensive:", "unicode": "1f614", "html": "&#128532;", "category": "Smileys & Emotion (face-sleepy)", "order": "43"},
	{"emoji": "😏", "name": "smirking face", "shortname": ":smirk:", "unicode": "1f60f", "html": "&#128527;", "category": "Smileys & Emotion (face-neutral-skeptical)", "order": "26"},
	{"emoji": "😁", "name": "beaming face with smiling eyes", "shortname": ":grin:", "unicode": "1f601", "html": "&#128513;", "category": "Smileys & Emotion (face-smiling)", "order": "2"},
	{"emoji": "😉", "name": "winking face", "shortname": ":wink:", "unicode": "1f609", "html": "&#128521;", "category": "Smileys & Emotion (face-smiling)", "order": "9"},
    {"emoji": "😳", "name": "flushed face", "shortname": ":flushed:", "unicode": "1f633", "html": "&#128563;", "category": "Smileys & Emotion (face-concerned)", "order": "63"},
    {"emoji": "😢", "name": "crying face", "shortname": ":cry:", "unicode": "1f622", "html": "&#128546;", "category": "Smileys & Emotion (face-concerned)", "order": "54"},
	{"emoji": "😎", "name": "smiling face with sunglasses", "shortname": ":sunglasses:", "unicode": "1f60e", "html": "&#128526;", "category": "Smileys & Emotion (face-glasses)", "order": "12"},  
    {"emoji": "😅", "name": "grinning face with sweat", "shortname": ":sweat_smile:", "unicode": "1f605", "html": "&#128517;", "category": "Smileys & Emotion (face-smiling)", "order": "7"},
    {"emoji": "😕", "name": "confused face", "shortname": ":confused:", "unicode": "1f615", "html": "&#128533;", "category": "Smileys & Emotion (face-concerned)", "order": "44"},
    {"emoji": "😤", "name": "face with steam from nose", "shortname": ":triumph:", "unicode": "1f624", "html": "&#128548;", "category": "Smileys & Emotion (face-negative)", "order": "53"},
    {"emoji": "✋", "name": "raised hand", "shortname": ":raised_hand:", "unicode": "270B", "html": "&#9995;", "category": "People & Body (hand-fingers-open)", "order": ""},
    {"emoji": "👋", "name": "waving hand", "shortname": ":wave:", "unicode": "1f44b", "html": "&#128075;", "category": "People & Body (hand-fingers-open)", "order": "1218"},
    {"emoji": "🔥", "name": "fire", "shortname": ":fire:", "unicode": "1f525", "html": "&#128293;", "category": "Travel & Places (sky & weather)", "order": "1753"},
    {"emoji": "😡", "name": "pouting face", "shortname": ":rage:", "unicode": "1f621", "html": "&#128545;", "category": "Smileys & Emotion (face-negative)", "order": "65"},
    {"emoji": "👊", "name": "oncoming fist", "shortname": ":oncoming_fist:", "unicode": "1F44A", "html": "&#128074;", "category": "People & Body (hand-fingers-closed)", "order": ""},
    {"emoji": "💪", "name": "flexed biceps", "shortname": ":muscle:", "unicode": "1f4aa", "html": "&#128170;", "category": "People & Body (body-parts)", "order": "1080"},
    {"emoji": "🎧", "name": "headphone", "shortname": ":headphones:", "unicode": "1f3a7", "html": "&#127911;", "category": "Objects (music)", "order": "1830"},
    {"emoji": "✅", "name": "check mark button", "shortname": ":white_check_mark:", "unicode": "2705", "html": "&#9989;", "category": "Symbols (other-symbol)", "order": "2078"},
]